export const BlogArticlesEng = [
    // {
    //     name: "title",
    //     url: "url",
    //     text1: ``,
    //     text2: ``,
    //     text3: ``,
    //     text4: ``,
    //     text5: ``,
    //     text6: ``,
    // },    
    {
        name: "Renault Sport Performance",
        url: "https://www.youtube.com/embed/xelNJF1D3Z0",
        text1: "Original music composition and sound design for the reveal of Renault Sport brand new Performance range of products.",
        text2: "",
        text3: "Video production : www.zystudio.fr",
        text4: "Communication agency : www.makheia.com",
        text5: "www.shop.renaultsport.com",
    },
    {
        name: "Mugler - Aura Experience 360°",
        url: "https://www.youtube.com/embed/y_PoyoQ2iYg",
        text1: `Création de musique originale et Sound Design Surround. 
        À l'occasion du lancement de son nouveau parfum Aura, la marque Mugler a choisi de faire découvrir son univers dans une expérience immersive exceptionnelle.`,
        text2: "",
        text3: "Réalisation agence Luxmodernis.",
        text4: "www.mugler.fr",
        text5: "www.luxmodernis.com",
    },
    {
        name: "Laser Game Evolution - Battle of Astaros",
        url: "https://www.youtube.com/embed/DmiZaT4w69k",
        text1: `Création de trois musiques originales pour le nouveau jeu d'arcade de la franchise Laser Game Evolution. Deux équipes s'affrontent dans une aventure intergalactique qui leur reserve son lot d'adrenaline.`,
        text2: ``,
        text3: `Realisation Agence Moonrise`,
        text4: `www.moonrise.fr`,
    },
    {
        name: "Picard Noel 2017",
        url: "https://www.youtube.com/embed/w6xpk3mQyvk",
        text1: `Création d'une musique originale pour une présentation en Mapping video à l'événement de lancement des gammes de noël 2017 de la chaine Picard.`,
        text2: ``,
        text3: `Réalisation film et 3D Agence Moonrise.`,
        text4: `www.picard.fr`,
        text5: `www.moonrise.fr`,
    },
    {
        name: "Engie - Vœux 2017",
        url: "https://www.youtube.com/embed/KFo0KgnLMEU",
        text1: `Le Groupe ENGIE vous présente ses meilleurs voeux 2018.
        Le Groupe inscrit la croissance responsable au cœur de ses métiers pour relever les grands enjeux de la transition énergétique.`,
        text2: ``,
        text3: `Réalisation Vidéo: Moonrise`,
        text4: `www.moonrise.fr`,
        text5: `www.engie.com`,
    },
    {
        name: "Fondation Sanofi Espoir",
        url: "https://www.youtube.com/embed/5X6JF8F8Hrw",
        text1: `Le Groupe Sanofi a créé la Fondation Sanofi Espoir en octobre 2010, pour capitaliser plus de 20 années d'engagement de solidarité nationale et internationale.`,
        text2: ``,
        text3: `Production vidéo:imageo`,
        text4: `www.imageo.fr`,
        text5: `www.fondation-sanofi-espoir.com`, 
    },
    {
        name: "ATIBT What is RIL",
        url: "https://www.youtube.com/embed/Bkc6Tib5U-M",
        text1: `L’Association Technique Internationale des Bois Tropicaux (ATIBT) a pour vocation d’être au service de la filière des bois tropicaux, de la forêt jusqu’au consommateur final. Dans cette video elle nous explique son action pour le programme RIL (Reduced Impact Logging)
        `,
        text2: ``,
        text3: `Sound Design et Synchro Musique par Release Studio.`,
        text4: `Réalisation Agence Imageo`,
        text5: `www.imageo.fr`,
    },
    {
        name: "The Music Vlog",
        url: "https://www.youtube.com/embed/441Yi1d7fQs",
        text1: `C'est un projet personnel ambitieux dans lequel s'est lancé notre producteur maison Clément Barbu.`,
        text2: `Composer et mettre en image chaque jour pendant un mois un court morceau et le poster sur les réseaux sociaux. `,
        text3: `Le résultat: une vaste palette sonore, une experience unique de composition et plus 1500 follower sur Instagram après 1 mois.`,
    },
    {
        name: "Campagne Excision parlons-en",
        url: "https://www.youtube.com/embed/V1QCyWsVL5s",
        text1: `Composition de musique originale et Sound Design pour cette campagne de prévention.
        Texte et Rap de l'artiste Dinamita appelé par l'association pour prêter sa voix et ses mots sans détours sur ce sujet sensible.`,
        text2: ``,
        text3: `Réalisation Agence imageo`,
        text4: `www.excisionparlonsen.org`,
        text5: `www.imageo.from`,
    },
    {
        name: "Agence National de Rénovation Urbaine",
        url: "https://www.youtube.com/embed/NA1lHFHyCkw",
        text1: `Composition de musique originale pour cette présentation du nouveau programme national de renouvellement urbain, un nouveau visage pour les quartiers.`,
        text2: ``,
        text3: `Un projet dirigé par l'agence Imageo`,
        text4: `www.anru.fr`,
        text5: `www.imageo.fr`,
    },
    {
        name: "TEDx Celsa",
        url: "https://www.youtube.com/embed/Ne46eszNRno",
        text1: `Release Studio est partenaire de TEDx Celsa organisé chez nos amis de Google France.`,
        text2: `le CELSA (Haute École des Sciences de l'Information et de la Communication) s’est lancé dans un projet ambitieux : l’organisation d’une conférence TEDx. L’objectif est à la fois de créer un événement fédérateur autour du partage d’idées et d’expériences inspirantes et de valoriser l’école à travers ses alumni.`,
        text3: ``,
        text4: `www.tedxcelsa.com`,
    },
]